### ISSUE TITLE
Improve swap toast management

### ISSUE THREAD

**Issue by usern3** [KongSwap/kong#194]
Make sure swap toasts don't prematurely disappear while the swap is still pending. There should always be at least 1 toast showing during the swap process so the user knows it's in progress and didn't fail.

Also, bump the position of the toasts down a bit so they don't block the navigation buttons. Maybe look into showing them in the bottom right corner if it can look good because then it's out of the way.

**Comment by CanerKocak** [comment]
> down a bit so they don't block the navigation buttons.

they remove onced clicked etc

but i do think they should be right side top feels natural and easier 

ill implement it so toast with "swap in progress" keeps showing until the status returns either error or success etc

**Comment by CanerKocak** [comment]
It works fine as is, so I'm closing this. I don't think we need to change the code. The messages clearly show what's happening during a swap.
