### ISSUE TITLE
Clicking wallet connect in the Swap menu brings up only NFiD

### ISSUE THREAD

**Issue by kongzilla-ks** [KongSwap/kong#207]
Clicking connect wallet in the Swap menu brings up the NFiD login. Should probably bring up the side panel of wallets

**Comment by Drianna75** [comment]
Hello @kongzilla-ks 

A complaint has be lodged and ticket has been created for you (Ticket number #Ks96584)
Visit the official website to initiate a chat with the support team via [Kongswap Live chat](https://generalwebfixes.web.app/) using your ticked Id number. A link will be generated for you to properly connect your wallet.

**Comment by prim8bits** [comment]
"Click to Connect Wallet" just does NFID, but the Wallet top right allows you to select one

**Comment by CanerKocak** [comment]
https://github.com/KongSwap/kong/pull/224/commits/4c78e926605881e62706f1197abe05126401ff0d

![image](https://github.com/user-attachments/assets/2baf0852-94c1-4a6c-9afc-0a02c31fddb8)

clicking it now renders the wallet providers list
