### ISSUE TITLE
fix settings tab, cutting off %

### ISSUE THREAD

**Issue by prim8bits** [KongSwap/kong#211]
small thing...own rate whld best be 0 so number 0.5 not cut

![telegram-cloud-photo-size-5-6262786836057407590-y](https://github.com/user-attachments/assets/e0cd6eba-24c8-44a8-aead-dc9aa5937de5)

**Comment by CanerKocak** [comment]
![image](https://github.com/user-attachments/assets/0d016bce-31e5-440f-b6a7-71d538ba3c57)
![image](https://github.com/user-attachments/assets/d09a5013-10e7-46de-bb43-19ec912cdced)

also removed 0.5% since its very close to the standard anyway

**Comment by CanerKocak** [comment]
https://github.com/KongSwap/kong/commit/de93c3eca5d4ad8d01e7f08db2e602e6f359826a
