### ISSUE TITLE
make copy principal/ account ID accessible form every page

### ISSUE THREAD

**Issue by prim8bits** [KongSwap/kong#212]
principal and account id should be copy and pastable from every page

its 2-3 clicks right now

**Comment by CanerKocak** [comment]
how? currently there are 3 buttons left side and 2 right side, what if we make settings just settings icon again, and add another button (albeit if logged in) with an copy icon with a profile icon and once clicked it will display "principal copied" etc?

something like this:
![image](https://github.com/user-attachments/assets/cff32976-c91d-428a-8ec4-75b91ff07486)


mobile:
![image](https://github.com/user-attachments/assets/3943b4ca-a72c-42ec-b13f-0b958b17c1ab)

**Comment by CanerKocak** [comment]
make it a bit smaller

![image](https://github.com/user-attachments/assets/ffef18ad-7193-4648-955a-a734d94b9997)

**Comment by CanerKocak** [comment]
https://github.com/KongSwap/kong/pull/224/commits/d1d3c5757aa69204c29d14a9c9e811a4c18e9c9b
