### ISSUE TITLE
bigint conversion error

### ISSUE THREAD

**Issue by prim8bits** [KongSwap/kong#219]
![telegram-cloud-photo-size-5-6265038635871092995-y](https://github.com/user-attachments/assets/0857894d-91cb-47e9-98d0-2c2b1a39ddfe)

**Comment by CanerKocak** [comment]
this also seems cketh related like https://github.com/KongSwap/kong/issues/220

**Comment by CanerKocak** [comment]
https://github.com/KongSwap/kong/pull/224/commits/00fe575e9eeb6675413af45e06745acd8584ea56
