### ISSUE TITLE
pressing max button gives Nan

### ISSUE THREAD

**Issue by prim8bits** [KongSwap/kong#220]
![telegram-cloud-photo-size-5-6265038635871092989-y](https://github.com/user-attachments/assets/1abbe291-781f-4d7a-8f23-652e36a25f14)

**Comment by CanerKocak** [comment]
this is not the case when i try to do it, maybe its related to ckETH specifically @prim8bits ? it has alot of decimals eth, so that might cause it?

**Comment by CanerKocak** [comment]
bob also causes same issue, think this might need bigger fee_fixed refactoring, gonna take my time with this one

**Comment by CanerKocak** [comment]
https://github.com/KongSwap/kong/pull/224/commits/00fe575e9eeb6675413af45e06745acd8584ea56
