### ISSUE TITLE
adding liquidity error

### ISSUE THREAD

**Issue by prim8bits** [KongSwap/kong#221]
![telegram-cloud-photo-size-4-5976727020412978557-y](https://github.com/user-attachments/assets/1d0d740d-af1a-4b1d-b4cb-8fb310599ac9)

**Comment by CanerKocak** [comment]
might be lagging price

honestly maybe add liquidity DOES NOT use any cached info at ALL since i dont think ppl would care for ADD LP taking 6s longer if it works

**Comment by CanerKocak** [comment]
with big number precision:
![image](https://github.com/user-attachments/assets/5b148f88-4166-4043-8f40-9e63ed156109)


without addedmprecision:
![image](https://github.com/user-attachments/assets/e33441ea-c6d4-4479-99fd-5d072e44def3)

so it might just be price action, the values really come from BE aswell double checked

however i also solved the incorrect value of ckusdt -> ckbtc ratio u can see on the SC aswell that it says 1ckbtc = 1k ckusdt haha, if only that was true :(

https://github.com/KongSwap/kong/commit/2d0d91df022be98ff7fddd797a7cbda1908bf1d8
