### ISSUE TITLE
active to inactive button behaviour issue

### ISSUE THREAD

**Issue by prim8bits** [KongSwap/kong#222]
button is greyed out and unclickable after i change ckBTC to ckETH

![telegram-cloud-photo-size-4-5976727020412978559-x](https://github.com/user-attachments/assets/4839fe1d-845d-4e56-918a-ed537aad9a19)

**Comment by CanerKocak** [comment]
seems like a reactivity thing, maybe we can also enhance the button in general

**Comment by CanerKocak** [comment]
those available balances are element inspect changed right 😲

**Comment by CanerKocak** [comment]
https://github.com/KongSwap/kong/commit/de44de3d53f3ca3790c35807373626d426d18b72
