### ISSUE TITLE
double $$ sign on the details page

### ISSUE THREAD

**Issue by prim8bits** [KongSwap/kong#223]
in the TVL $$

![image](https://github.com/user-attachments/assets/40de2b53-7dc0-4a67-9ef8-2616b05d427b)

**Comment by CanerKocak** [comment]
![image](https://github.com/user-attachments/assets/1fd454fc-c203-445f-9488-ee8b1f768d61)
![image](https://github.com/user-attachments/assets/55a4870a-c05d-4692-81e4-3b17bced3eac)


when clicked details the doulbe $$ is gone + i made it so it formats a more detailed number aswell as to comply with a "details page"

https://github.com/KongSwap/kong/pull/224/commits/3dc06ecb8cf2e6eb9945cd5bc4e06794d8d24e5e
