### ISSUE TITLE
Normie Friendly wallet naming conventions

### ISSUE THREAD

**Issue by prim8bits** [KongSwap/kong#251]
Naming conventions around wallets and principals need to become clearer for new users, we need to update the terminology: 

Account details -> Wallet Address

Principal Address - Used to send and receive all IC tokens to and from KongSwap 

Account Address (CEX address) - Used when sending ICP to and from  Binance, Coinbase, Bybit, Crypto.com and other centralized exchanges

**Comment by CanerKocak** [comment]
https://github.com/KongSwap/kong/compare/249-add-support-for-transfers-to-account-ids?expand=1
